// AUTO-GENERATED by scripts/extract-icons.mjs — do not edit by hand.
// Curated lucide icons as raw SVG node data, shipped for the design canvas.
import type { GraphicNode } from '../schemas/scene.js';

export interface IconDef {
  id: string;
  label: string;
  tags: string[];
  viewBox: number;
  nodes: GraphicNode[];
}

export const ICONS: ReadonlyArray<IconDef> = [
  {
    "id": "building-2",
    "label": "Building",
    "tags": [
      "city",
      "building",
      "skyline",
      "lagos"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z"
        }
      ],
      [
        "path",
        {
          "d": "M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2"
        }
      ],
      [
        "path",
        {
          "d": "M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2"
        }
      ],
      [
        "path",
        {
          "d": "M10 6h4"
        }
      ],
      [
        "path",
        {
          "d": "M10 10h4"
        }
      ],
      [
        "path",
        {
          "d": "M10 14h4"
        }
      ],
      [
        "path",
        {
          "d": "M10 18h4"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "building",
    "label": "Tower",
    "tags": [
      "city",
      "building",
      "skyline"
    ],
    "nodes": [
      [
        "rect",
        {
          "width": "16",
          "height": "20",
          "x": "4",
          "y": "2",
          "rx": "2",
          "ry": "2"
        }
      ],
      [
        "path",
        {
          "d": "M9 22v-4h6v4"
        }
      ],
      [
        "path",
        {
          "d": "M8 6h.01"
        }
      ],
      [
        "path",
        {
          "d": "M16 6h.01"
        }
      ],
      [
        "path",
        {
          "d": "M12 6h.01"
        }
      ],
      [
        "path",
        {
          "d": "M12 10h.01"
        }
      ],
      [
        "path",
        {
          "d": "M12 14h.01"
        }
      ],
      [
        "path",
        {
          "d": "M16 10h.01"
        }
      ],
      [
        "path",
        {
          "d": "M16 14h.01"
        }
      ],
      [
        "path",
        {
          "d": "M8 10h.01"
        }
      ],
      [
        "path",
        {
          "d": "M8 14h.01"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "landmark",
    "label": "Landmark",
    "tags": [
      "city",
      "monument",
      "building"
    ],
    "nodes": [
      [
        "line",
        {
          "x1": "3",
          "x2": "21",
          "y1": "22",
          "y2": "22"
        }
      ],
      [
        "line",
        {
          "x1": "6",
          "x2": "6",
          "y1": "18",
          "y2": "11"
        }
      ],
      [
        "line",
        {
          "x1": "10",
          "x2": "10",
          "y1": "18",
          "y2": "11"
        }
      ],
      [
        "line",
        {
          "x1": "14",
          "x2": "14",
          "y1": "18",
          "y2": "11"
        }
      ],
      [
        "line",
        {
          "x1": "18",
          "x2": "18",
          "y1": "18",
          "y2": "11"
        }
      ],
      [
        "polygon",
        {
          "points": "12 2 20 7 4 7"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "factory",
    "label": "Factory",
    "tags": [
      "city",
      "industry"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M2 20a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8l-7 5V8l-7 5V4a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z"
        }
      ],
      [
        "path",
        {
          "d": "M17 18h1"
        }
      ],
      [
        "path",
        {
          "d": "M12 18h1"
        }
      ],
      [
        "path",
        {
          "d": "M7 18h1"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "store",
    "label": "Store",
    "tags": [
      "city",
      "shop"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "m2 7 4.41-4.41A2 2 0 0 1 7.83 2h8.34a2 2 0 0 1 1.42.59L22 7"
        }
      ],
      [
        "path",
        {
          "d": "M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"
        }
      ],
      [
        "path",
        {
          "d": "M15 22v-4a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v4"
        }
      ],
      [
        "path",
        {
          "d": "M2 7h20"
        }
      ],
      [
        "path",
        {
          "d": "M22 7v3a2 2 0 0 1-2 2a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 16 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 12 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 8 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 4 12a2 2 0 0 1-2-2V7"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "church",
    "label": "Church",
    "tags": [
      "faith",
      "building"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M10 9h4"
        }
      ],
      [
        "path",
        {
          "d": "M12 7v5"
        }
      ],
      [
        "path",
        {
          "d": "M14 22v-4a2 2 0 0 0-4 0v4"
        }
      ],
      [
        "path",
        {
          "d": "M18 22V5.618a1 1 0 0 0-.553-.894l-4.553-2.277a2 2 0 0 0-1.788 0L6.553 4.724A1 1 0 0 0 6 5.618V22"
        }
      ],
      [
        "path",
        {
          "d": "m18 7 3.447 1.724a1 1 0 0 1 .553.894V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9.618a1 1 0 0 1 .553-.894L6 7"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "castle",
    "label": "Castle",
    "tags": [
      "building",
      "royal"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M22 20v-9H2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2Z"
        }
      ],
      [
        "path",
        {
          "d": "M18 11V4H6v7"
        }
      ],
      [
        "path",
        {
          "d": "M15 22v-4a3 3 0 0 0-3-3a3 3 0 0 0-3 3v4"
        }
      ],
      [
        "path",
        {
          "d": "M22 11V9"
        }
      ],
      [
        "path",
        {
          "d": "M2 11V9"
        }
      ],
      [
        "path",
        {
          "d": "M6 4V2"
        }
      ],
      [
        "path",
        {
          "d": "M18 4V2"
        }
      ],
      [
        "path",
        {
          "d": "M10 4V2"
        }
      ],
      [
        "path",
        {
          "d": "M14 4V2"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "sun",
    "label": "Sun",
    "tags": [
      "nature",
      "summer",
      "weather"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "4"
        }
      ],
      [
        "path",
        {
          "d": "M12 2v2"
        }
      ],
      [
        "path",
        {
          "d": "M12 20v2"
        }
      ],
      [
        "path",
        {
          "d": "m4.93 4.93 1.41 1.41"
        }
      ],
      [
        "path",
        {
          "d": "m17.66 17.66 1.41 1.41"
        }
      ],
      [
        "path",
        {
          "d": "M2 12h2"
        }
      ],
      [
        "path",
        {
          "d": "M20 12h2"
        }
      ],
      [
        "path",
        {
          "d": "m6.34 17.66-1.41 1.41"
        }
      ],
      [
        "path",
        {
          "d": "m19.07 4.93-1.41 1.41"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "moon",
    "label": "Moon",
    "tags": [
      "nature",
      "night",
      "weather"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "cloud",
    "label": "Cloud",
    "tags": [
      "nature",
      "weather",
      "sky"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "star",
    "label": "Star",
    "tags": [
      "star",
      "favorite",
      "night"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "sparkles",
    "label": "Sparkles",
    "tags": [
      "sparkle",
      "magic",
      "shine"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"
        }
      ],
      [
        "path",
        {
          "d": "M20 3v4"
        }
      ],
      [
        "path",
        {
          "d": "M22 5h-4"
        }
      ],
      [
        "path",
        {
          "d": "M4 17v2"
        }
      ],
      [
        "path",
        {
          "d": "M5 18H3"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "flame",
    "label": "Flame",
    "tags": [
      "fire",
      "hot",
      "energy"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "zap",
    "label": "Bolt",
    "tags": [
      "lightning",
      "energy",
      "power"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "droplet",
    "label": "Droplet",
    "tags": [
      "water",
      "nature"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M12 22a7 7 0 0 0 7-7c0-2-1-3.9-3-5.5s-3.5-4-4-6.5c-.5 2.5-2 4.9-4 6.5C6 11.1 5 13 5 15a7 7 0 0 0 7 7z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "snowflake",
    "label": "Snowflake",
    "tags": [
      "winter",
      "cold",
      "nature"
    ],
    "nodes": [
      [
        "line",
        {
          "x1": "2",
          "x2": "22",
          "y1": "12",
          "y2": "12"
        }
      ],
      [
        "line",
        {
          "x1": "12",
          "x2": "12",
          "y1": "2",
          "y2": "22"
        }
      ],
      [
        "path",
        {
          "d": "m20 16-4-4 4-4"
        }
      ],
      [
        "path",
        {
          "d": "m4 8 4 4-4 4"
        }
      ],
      [
        "path",
        {
          "d": "m16 4-4 4-4-4"
        }
      ],
      [
        "path",
        {
          "d": "m8 20 4-4 4 4"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "leaf",
    "label": "Leaf",
    "tags": [
      "nature",
      "plant",
      "eco"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z"
        }
      ],
      [
        "path",
        {
          "d": "M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "trees",
    "label": "Trees",
    "tags": [
      "nature",
      "forest",
      "plant"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M10 10v.2A3 3 0 0 1 8.9 16H5a3 3 0 0 1-1-5.8V10a3 3 0 0 1 6 0Z"
        }
      ],
      [
        "path",
        {
          "d": "M7 16v6"
        }
      ],
      [
        "path",
        {
          "d": "M13 19v3"
        }
      ],
      [
        "path",
        {
          "d": "M12 19h8.3a1 1 0 0 0 .7-1.7L18 14h.3a1 1 0 0 0 .7-1.7L16 9h.2a1 1 0 0 0 .8-1.7L13 3l-1.4 1.5"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "flower",
    "label": "Flower",
    "tags": [
      "nature",
      "floral",
      "spring"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "3"
        }
      ],
      [
        "path",
        {
          "d": "M12 16.5A4.5 4.5 0 1 1 7.5 12 4.5 4.5 0 1 1 12 7.5a4.5 4.5 0 1 1 4.5 4.5 4.5 4.5 0 1 1-4.5 4.5"
        }
      ],
      [
        "path",
        {
          "d": "M12 7.5V9"
        }
      ],
      [
        "path",
        {
          "d": "M7.5 12H9"
        }
      ],
      [
        "path",
        {
          "d": "M16.5 12H15"
        }
      ],
      [
        "path",
        {
          "d": "M12 16.5V15"
        }
      ],
      [
        "path",
        {
          "d": "m8 8 1.88 1.88"
        }
      ],
      [
        "path",
        {
          "d": "M14.12 9.88 16 8"
        }
      ],
      [
        "path",
        {
          "d": "m8 16 1.88-1.88"
        }
      ],
      [
        "path",
        {
          "d": "M14.12 14.12 16 16"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "mountain",
    "label": "Mountain",
    "tags": [
      "nature",
      "outdoor",
      "adventure"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "m8 3 4 8 5-5 5 15H2L8 3z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "waves",
    "label": "Waves",
    "tags": [
      "water",
      "ocean",
      "sea"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M2 6c.6.5 1.2 1 2.5 1C7 7 7 5 9.5 5c2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"
        }
      ],
      [
        "path",
        {
          "d": "M2 12c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"
        }
      ],
      [
        "path",
        {
          "d": "M2 18c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "rainbow",
    "label": "Rainbow",
    "tags": [
      "nature",
      "colorful",
      "pride"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M22 17a10 10 0 0 0-20 0"
        }
      ],
      [
        "path",
        {
          "d": "M6 17a6 6 0 0 1 12 0"
        }
      ],
      [
        "path",
        {
          "d": "M10 17a2 2 0 0 1 4 0"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "heart",
    "label": "Heart",
    "tags": [
      "love",
      "valentine",
      "like"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "heart-handshake",
    "label": "Care",
    "tags": [
      "love",
      "care",
      "kindness"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"
        }
      ],
      [
        "path",
        {
          "d": "M12 5 9.04 7.96a2.17 2.17 0 0 0 0 3.08c.82.82 2.13.85 3 .07l2.07-1.9a2.82 2.82 0 0 1 3.79 0l2.96 2.66"
        }
      ],
      [
        "path",
        {
          "d": "m18 15-2-2"
        }
      ],
      [
        "path",
        {
          "d": "m15 18-2-2"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "smile",
    "label": "Smile",
    "tags": [
      "face",
      "happy",
      "emoji"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      ],
      [
        "path",
        {
          "d": "M8 14s1.5 2 4 2 4-2 4-2"
        }
      ],
      [
        "line",
        {
          "x1": "9",
          "x2": "9.01",
          "y1": "9",
          "y2": "9"
        }
      ],
      [
        "line",
        {
          "x1": "15",
          "x2": "15.01",
          "y1": "9",
          "y2": "9"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "laugh",
    "label": "Laugh",
    "tags": [
      "face",
      "happy",
      "fun"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      ],
      [
        "path",
        {
          "d": "M18 13a6 6 0 0 1-6 5 6 6 0 0 1-6-5h12Z"
        }
      ],
      [
        "line",
        {
          "x1": "9",
          "x2": "9.01",
          "y1": "9",
          "y2": "9"
        }
      ],
      [
        "line",
        {
          "x1": "15",
          "x2": "15.01",
          "y1": "9",
          "y2": "9"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "music",
    "label": "Music note",
    "tags": [
      "music",
      "song",
      "sound"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M9 18V5l12-2v13"
        }
      ],
      [
        "circle",
        {
          "cx": "6",
          "cy": "18",
          "r": "3"
        }
      ],
      [
        "circle",
        {
          "cx": "18",
          "cy": "16",
          "r": "3"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "music-2",
    "label": "Note",
    "tags": [
      "music",
      "song"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "8",
          "cy": "18",
          "r": "4"
        }
      ],
      [
        "path",
        {
          "d": "M12 18V2l7 4"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "headphones",
    "label": "Headphones",
    "tags": [
      "music",
      "audio",
      "dj"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M3 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-7a9 9 0 0 1 18 0v7a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "guitar",
    "label": "Guitar",
    "tags": [
      "music",
      "instrument",
      "rock"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "m11.9 12.1 4.514-4.514"
        }
      ],
      [
        "path",
        {
          "d": "M20.1 2.3a1 1 0 0 0-1.4 0l-1.114 1.114A2 2 0 0 0 17 4.828v1.344a2 2 0 0 1-.586 1.414A2 2 0 0 1 17.828 7h1.344a2 2 0 0 0 1.414-.586L21.7 5.3a1 1 0 0 0 0-1.4z"
        }
      ],
      [
        "path",
        {
          "d": "m6 16 2 2"
        }
      ],
      [
        "path",
        {
          "d": "M8.2 9.9C8.7 8.8 9.8 8 11 8c2.8 0 5 2.2 5 5 0 1.2-.8 2.3-1.9 2.8l-.9.4A2 2 0 0 0 12 18a4 4 0 0 1-4 4c-3.3 0-6-2.7-6-6a4 4 0 0 1 4-4 2 2 0 0 0 1.8-1.2z"
        }
      ],
      [
        "circle",
        {
          "cx": "11.5",
          "cy": "12.5",
          "r": ".5",
          "fill": "currentColor"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "mic",
    "label": "Mic",
    "tags": [
      "music",
      "sing",
      "sound"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z"
        }
      ],
      [
        "path",
        {
          "d": "M19 10v2a7 7 0 0 1-14 0v-2"
        }
      ],
      [
        "line",
        {
          "x1": "12",
          "x2": "12",
          "y1": "19",
          "y2": "22"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "disc",
    "label": "Disc",
    "tags": [
      "music",
      "vinyl",
      "dj"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      ],
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "2"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "radio",
    "label": "Radio",
    "tags": [
      "music",
      "sound"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M4.9 19.1C1 15.2 1 8.8 4.9 4.9"
        }
      ],
      [
        "path",
        {
          "d": "M7.8 16.2c-2.3-2.3-2.3-6.1 0-8.5"
        }
      ],
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "2"
        }
      ],
      [
        "path",
        {
          "d": "M16.2 7.8c2.3 2.3 2.3 6.1 0 8.5"
        }
      ],
      [
        "path",
        {
          "d": "M19.1 4.9C23 8.8 23 15.1 19.1 19"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "trophy",
    "label": "Trophy",
    "tags": [
      "sport",
      "win",
      "champion"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M6 9H4.5a2.5 2.5 0 0 1 0-5H6"
        }
      ],
      [
        "path",
        {
          "d": "M18 9h1.5a2.5 2.5 0 0 0 0-5H18"
        }
      ],
      [
        "path",
        {
          "d": "M4 22h16"
        }
      ],
      [
        "path",
        {
          "d": "M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22"
        }
      ],
      [
        "path",
        {
          "d": "M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22"
        }
      ],
      [
        "path",
        {
          "d": "M18 2H6v7a6 6 0 0 0 12 0V2Z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "medal",
    "label": "Medal",
    "tags": [
      "sport",
      "win",
      "award"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M7.21 15 2.66 7.14a2 2 0 0 1 .13-2.2L4.4 2.8A2 2 0 0 1 6 2h12a2 2 0 0 1 1.6.8l1.6 2.14a2 2 0 0 1 .14 2.2L16.79 15"
        }
      ],
      [
        "path",
        {
          "d": "M11 12 5.12 2.2"
        }
      ],
      [
        "path",
        {
          "d": "m13 12 5.88-9.8"
        }
      ],
      [
        "path",
        {
          "d": "M8 7h8"
        }
      ],
      [
        "circle",
        {
          "cx": "12",
          "cy": "17",
          "r": "5"
        }
      ],
      [
        "path",
        {
          "d": "M12 18v-2h-.5"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "dumbbell",
    "label": "Dumbbell",
    "tags": [
      "sport",
      "gym",
      "fitness"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M14.4 14.4 9.6 9.6"
        }
      ],
      [
        "path",
        {
          "d": "M18.657 21.485a2 2 0 1 1-2.829-2.828l-1.767 1.768a2 2 0 1 1-2.829-2.829l6.364-6.364a2 2 0 1 1 2.829 2.829l-1.768 1.767a2 2 0 1 1 2.828 2.829z"
        }
      ],
      [
        "path",
        {
          "d": "m21.5 21.5-1.4-1.4"
        }
      ],
      [
        "path",
        {
          "d": "M3.9 3.9 2.5 2.5"
        }
      ],
      [
        "path",
        {
          "d": "M6.404 12.768a2 2 0 1 1-2.829-2.829l1.768-1.767a2 2 0 1 1-2.828-2.829l2.828-2.828a2 2 0 1 1 2.829 2.828l1.767-1.768a2 2 0 1 1 2.829 2.829z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "bike",
    "label": "Bike",
    "tags": [
      "sport",
      "cycle"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "18.5",
          "cy": "17.5",
          "r": "3.5"
        }
      ],
      [
        "circle",
        {
          "cx": "5.5",
          "cy": "17.5",
          "r": "3.5"
        }
      ],
      [
        "circle",
        {
          "cx": "15",
          "cy": "5",
          "r": "1"
        }
      ],
      [
        "path",
        {
          "d": "M12 17.5V14l-3-3 4-3 2 3h2"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "footprints",
    "label": "Footprints",
    "tags": [
      "walk",
      "run",
      "sport"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M4 16v-2.38C4 11.5 2.97 10.5 3 8c.03-2.72 1.49-6 4.5-6C9.37 2 10 3.8 10 5.5c0 3.11-2 5.66-2 8.68V16a2 2 0 1 1-4 0Z"
        }
      ],
      [
        "path",
        {
          "d": "M20 20v-2.38c0-2.12 1.03-3.12 1-5.62-.03-2.72-1.49-6-4.5-6C14.63 6 14 7.8 14 9.5c0 3.11 2 5.66 2 8.68V20a2 2 0 1 0 4 0Z"
        }
      ],
      [
        "path",
        {
          "d": "M16 17h4"
        }
      ],
      [
        "path",
        {
          "d": "M4 13h4"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "target",
    "label": "Target",
    "tags": [
      "aim",
      "goal",
      "sport"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      ],
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "6"
        }
      ],
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "2"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "coffee",
    "label": "Coffee",
    "tags": [
      "food",
      "drink",
      "cafe"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M10 2v2"
        }
      ],
      [
        "path",
        {
          "d": "M14 2v2"
        }
      ],
      [
        "path",
        {
          "d": "M16 8a1 1 0 0 1 1 1v8a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1h14a4 4 0 1 1 0 8h-1"
        }
      ],
      [
        "path",
        {
          "d": "M6 2v2"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "pizza",
    "label": "Pizza",
    "tags": [
      "food",
      "fun"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "m12 14-1 1"
        }
      ],
      [
        "path",
        {
          "d": "m13.75 18.25-1.25 1.42"
        }
      ],
      [
        "path",
        {
          "d": "M17.775 5.654a15.68 15.68 0 0 0-12.121 12.12"
        }
      ],
      [
        "path",
        {
          "d": "M18.8 9.3a1 1 0 0 0 2.1 7.7"
        }
      ],
      [
        "path",
        {
          "d": "M21.964 20.732a1 1 0 0 1-1.232 1.232l-18-5a1 1 0 0 1-.695-1.232A19.68 19.68 0 0 1 15.732 2.037a1 1 0 0 1 1.232.695z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "ice-cream-cone",
    "label": "Ice cream",
    "tags": [
      "food",
      "summer"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "m7 11 4.08 10.35a1 1 0 0 0 1.84 0L17 11"
        }
      ],
      [
        "path",
        {
          "d": "M17 7A5 5 0 0 0 7 7"
        }
      ],
      [
        "path",
        {
          "d": "M17 7a2 2 0 0 1 0 4H7a2 2 0 0 1 0-4"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "cake",
    "label": "Cake",
    "tags": [
      "food",
      "birthday",
      "party"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M20 21v-8a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8"
        }
      ],
      [
        "path",
        {
          "d": "M4 16s.5-1 2-1 2.5 2 4 2 2.5-2 4-2 2.5 2 4 2 2-1 2-1"
        }
      ],
      [
        "path",
        {
          "d": "M2 21h20"
        }
      ],
      [
        "path",
        {
          "d": "M7 8v3"
        }
      ],
      [
        "path",
        {
          "d": "M12 8v3"
        }
      ],
      [
        "path",
        {
          "d": "M17 8v3"
        }
      ],
      [
        "path",
        {
          "d": "M7 4h.01"
        }
      ],
      [
        "path",
        {
          "d": "M12 4h.01"
        }
      ],
      [
        "path",
        {
          "d": "M17 4h.01"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "beer",
    "label": "Beer",
    "tags": [
      "drink",
      "party"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M17 11h1a3 3 0 0 1 0 6h-1"
        }
      ],
      [
        "path",
        {
          "d": "M9 12v6"
        }
      ],
      [
        "path",
        {
          "d": "M13 12v6"
        }
      ],
      [
        "path",
        {
          "d": "M14 7.5c-1 0-1.44.5-3 .5s-2-.5-3-.5-1.72.5-2.5.5a2.5 2.5 0 0 1 0-5c.78 0 1.57.5 2.5.5S9.44 2 11 2s2 1.5 3 1.5 1.72-.5 2.5-.5a2.5 2.5 0 0 1 0 5c-.78 0-1.5-.5-2.5-.5Z"
        }
      ],
      [
        "path",
        {
          "d": "M5 8v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V8"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "cup-soda",
    "label": "Soda",
    "tags": [
      "drink",
      "food"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "m6 8 1.75 12.28a2 2 0 0 0 2 1.72h4.54a2 2 0 0 0 2-1.72L18 8"
        }
      ],
      [
        "path",
        {
          "d": "M5 8h14"
        }
      ],
      [
        "path",
        {
          "d": "M7 15a6.47 6.47 0 0 1 5 0 6.47 6.47 0 0 0 5 0"
        }
      ],
      [
        "path",
        {
          "d": "m12 8 1-6h2"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "cherry",
    "label": "Cherry",
    "tags": [
      "food",
      "fruit"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M2 17a5 5 0 0 0 10 0c0-2.76-2.5-5-5-3-2.5-2-5 .24-5 3Z"
        }
      ],
      [
        "path",
        {
          "d": "M12 17a5 5 0 0 0 10 0c0-2.76-2.5-5-5-3-2.5-2-5 .24-5 3Z"
        }
      ],
      [
        "path",
        {
          "d": "M7 14c3.22-2.91 4.29-8.75 5-12 1.66 2.38 4.94 9 5 12"
        }
      ],
      [
        "path",
        {
          "d": "M22 9c-4.29 0-7.14-2.33-10-7 5.71 0 10 4.67 10 7Z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "crown",
    "label": "Crown",
    "tags": [
      "royal",
      "king",
      "queen",
      "luxury"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z"
        }
      ],
      [
        "path",
        {
          "d": "M5 21h14"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "gem",
    "label": "Gem",
    "tags": [
      "luxury",
      "diamond",
      "shine"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M6 3h12l4 6-10 13L2 9Z"
        }
      ],
      [
        "path",
        {
          "d": "M11 3 8 9l4 13 4-13-3-6"
        }
      ],
      [
        "path",
        {
          "d": "M2 9h20"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "rocket",
    "label": "Rocket",
    "tags": [
      "space",
      "launch",
      "startup"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z"
        }
      ],
      [
        "path",
        {
          "d": "m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z"
        }
      ],
      [
        "path",
        {
          "d": "M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0"
        }
      ],
      [
        "path",
        {
          "d": "M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "anchor",
    "label": "Anchor",
    "tags": [
      "sea",
      "nautical"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M12 22V8"
        }
      ],
      [
        "path",
        {
          "d": "M5 12H2a10 10 0 0 0 20 0h-3"
        }
      ],
      [
        "circle",
        {
          "cx": "12",
          "cy": "5",
          "r": "3"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "skull",
    "label": "Skull",
    "tags": [
      "edgy",
      "street",
      "danger"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "m12.5 17-.5-1-.5 1h1z"
        }
      ],
      [
        "path",
        {
          "d": "M15 22a1 1 0 0 0 1-1v-1a2 2 0 0 0 1.56-3.25 8 8 0 1 0-11.12 0A2 2 0 0 0 8 20v1a1 1 0 0 0 1 1z"
        }
      ],
      [
        "circle",
        {
          "cx": "15",
          "cy": "12",
          "r": "1"
        }
      ],
      [
        "circle",
        {
          "cx": "9",
          "cy": "12",
          "r": "1"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "ghost",
    "label": "Ghost",
    "tags": [
      "spooky",
      "fun",
      "halloween"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M9 10h.01"
        }
      ],
      [
        "path",
        {
          "d": "M15 10h.01"
        }
      ],
      [
        "path",
        {
          "d": "M12 2a8 8 0 0 0-8 8v12l3-3 2.5 2.5L12 19l2.5 2.5L17 19l3 3V10a8 8 0 0 0-8-8z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "bot",
    "label": "Robot",
    "tags": [
      "tech",
      "ai",
      "fun"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M12 8V4H8"
        }
      ],
      [
        "rect",
        {
          "width": "16",
          "height": "12",
          "x": "4",
          "y": "8",
          "rx": "2"
        }
      ],
      [
        "path",
        {
          "d": "M2 14h2"
        }
      ],
      [
        "path",
        {
          "d": "M20 14h2"
        }
      ],
      [
        "path",
        {
          "d": "M15 13v2"
        }
      ],
      [
        "path",
        {
          "d": "M9 13v2"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "cpu",
    "label": "Chip",
    "tags": [
      "tech",
      "circuit"
    ],
    "nodes": [
      [
        "rect",
        {
          "width": "16",
          "height": "16",
          "x": "4",
          "y": "4",
          "rx": "2"
        }
      ],
      [
        "rect",
        {
          "width": "6",
          "height": "6",
          "x": "9",
          "y": "9",
          "rx": "1"
        }
      ],
      [
        "path",
        {
          "d": "M15 2v2"
        }
      ],
      [
        "path",
        {
          "d": "M15 20v2"
        }
      ],
      [
        "path",
        {
          "d": "M2 15h2"
        }
      ],
      [
        "path",
        {
          "d": "M2 9h2"
        }
      ],
      [
        "path",
        {
          "d": "M20 15h2"
        }
      ],
      [
        "path",
        {
          "d": "M20 9h2"
        }
      ],
      [
        "path",
        {
          "d": "M9 2v2"
        }
      ],
      [
        "path",
        {
          "d": "M9 20v2"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "globe",
    "label": "Globe",
    "tags": [
      "world",
      "travel",
      "earth"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      ],
      [
        "path",
        {
          "d": "M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"
        }
      ],
      [
        "path",
        {
          "d": "M2 12h20"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "map-pin",
    "label": "Pin",
    "tags": [
      "location",
      "travel",
      "map"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"
        }
      ],
      [
        "circle",
        {
          "cx": "12",
          "cy": "10",
          "r": "3"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "plane",
    "label": "Plane",
    "tags": [
      "travel",
      "fly"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "car",
    "label": "Car",
    "tags": [
      "drive",
      "auto"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2"
        }
      ],
      [
        "circle",
        {
          "cx": "7",
          "cy": "17",
          "r": "2"
        }
      ],
      [
        "path",
        {
          "d": "M9 17h6"
        }
      ],
      [
        "circle",
        {
          "cx": "17",
          "cy": "17",
          "r": "2"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "camera",
    "label": "Camera",
    "tags": [
      "photo",
      "media"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z"
        }
      ],
      [
        "circle",
        {
          "cx": "12",
          "cy": "13",
          "r": "3"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "gamepad",
    "label": "Gamepad",
    "tags": [
      "game",
      "play"
    ],
    "nodes": [
      [
        "line",
        {
          "x1": "6",
          "x2": "10",
          "y1": "12",
          "y2": "12"
        }
      ],
      [
        "line",
        {
          "x1": "8",
          "x2": "8",
          "y1": "10",
          "y2": "14"
        }
      ],
      [
        "line",
        {
          "x1": "15",
          "x2": "15.01",
          "y1": "13",
          "y2": "13"
        }
      ],
      [
        "line",
        {
          "x1": "18",
          "x2": "18.01",
          "y1": "11",
          "y2": "11"
        }
      ],
      [
        "rect",
        {
          "width": "20",
          "height": "12",
          "x": "2",
          "y": "6",
          "rx": "2"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "paw-print",
    "label": "Paw",
    "tags": [
      "animal",
      "pet"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "11",
          "cy": "4",
          "r": "2"
        }
      ],
      [
        "circle",
        {
          "cx": "18",
          "cy": "8",
          "r": "2"
        }
      ],
      [
        "circle",
        {
          "cx": "20",
          "cy": "16",
          "r": "2"
        }
      ],
      [
        "path",
        {
          "d": "M9 10a5 5 0 0 1 5 5v3.5a3.5 3.5 0 0 1-6.84 1.045Q6.52 17.48 4.46 16.84A3.5 3.5 0 0 1 5.5 10Z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "cat",
    "label": "Cat",
    "tags": [
      "animal",
      "pet"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M12 5c.67 0 1.35.09 2 .26 1.78-2 5.03-2.84 6.42-2.26 1.4.58-.42 7-.42 7 .57 1.07 1 2.24 1 3.44C21 17.9 16.97 21 12 21s-9-3-9-7.56c0-1.25.5-2.4 1-3.44 0 0-1.89-6.42-.5-7 1.39-.58 4.72.23 6.5 2.23A9.04 9.04 0 0 1 12 5Z"
        }
      ],
      [
        "path",
        {
          "d": "M8 14v.5"
        }
      ],
      [
        "path",
        {
          "d": "M16 14v.5"
        }
      ],
      [
        "path",
        {
          "d": "M11.25 16.25h1.5L12 17l-.75-.75Z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "dog",
    "label": "Dog",
    "tags": [
      "animal",
      "pet"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M11.25 16.25h1.5L12 17z"
        }
      ],
      [
        "path",
        {
          "d": "M16 14v.5"
        }
      ],
      [
        "path",
        {
          "d": "M4.42 11.247A13.152 13.152 0 0 0 4 14.556C4 18.728 7.582 21 12 21s8-2.272 8-6.444a11.702 11.702 0 0 0-.493-3.309"
        }
      ],
      [
        "path",
        {
          "d": "M8 14v.5"
        }
      ],
      [
        "path",
        {
          "d": "M8.5 8.5c-.384 1.05-1.083 2.028-2.344 2.5-1.931.722-3.576-.297-3.656-1-.113-.994 1.177-6.53 4-7 1.923-.321 3.651.845 3.651 2.235A7.497 7.497 0 0 1 14 5.277c0-1.39 1.844-2.598 3.767-2.277 2.823.47 4.113 6.006 4 7-.08.703-1.725 1.722-3.656 1-1.261-.472-1.855-1.45-2.239-2.5"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "bird",
    "label": "Bird",
    "tags": [
      "animal",
      "nature"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M16 7h.01"
        }
      ],
      [
        "path",
        {
          "d": "M3.4 18H12a8 8 0 0 0 8-8V7a4 4 0 0 0-7.28-2.3L2 20"
        }
      ],
      [
        "path",
        {
          "d": "m20 7 2 .5-2 .5"
        }
      ],
      [
        "path",
        {
          "d": "M10 18v3"
        }
      ],
      [
        "path",
        {
          "d": "M14 17.75V21"
        }
      ],
      [
        "path",
        {
          "d": "M7 18a6 6 0 0 0 3.84-10.61"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "fish",
    "label": "Fish",
    "tags": [
      "animal",
      "sea"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M6.5 12c.94-3.46 4.94-6 8.5-6 3.56 0 6.06 2.54 7 6-.94 3.47-3.44 6-7 6s-7.56-2.53-8.5-6Z"
        }
      ],
      [
        "path",
        {
          "d": "M18 12v.5"
        }
      ],
      [
        "path",
        {
          "d": "M16 17.93a9.77 9.77 0 0 1 0-11.86"
        }
      ],
      [
        "path",
        {
          "d": "M7 10.67C7 8 5.58 5.97 2.73 5.5c-1 1.5-1 5 .23 6.5-1.24 1.5-1.24 5-.23 6.5C5.58 18.03 7 16 7 13.33"
        }
      ],
      [
        "path",
        {
          "d": "M10.46 7.26C10.2 5.88 9.17 4.24 8 3h5.8a2 2 0 0 1 1.98 1.67l.23 1.4"
        }
      ],
      [
        "path",
        {
          "d": "m16.01 17.93-.23 1.4A2 2 0 0 1 13.8 21H9.5a5.96 5.96 0 0 0 1.49-3.98"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "feather",
    "label": "Feather",
    "tags": [
      "light",
      "nature",
      "write"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M12.67 19a2 2 0 0 0 1.416-.588l6.154-6.172a6 6 0 0 0-8.49-8.49L5.586 9.914A2 2 0 0 0 5 11.328V18a1 1 0 0 0 1 1z"
        }
      ],
      [
        "path",
        {
          "d": "M16 8 2 22"
        }
      ],
      [
        "path",
        {
          "d": "M17.5 15H9"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "crosshair",
    "label": "Crosshair",
    "tags": [
      "aim",
      "target"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      ],
      [
        "line",
        {
          "x1": "22",
          "x2": "18",
          "y1": "12",
          "y2": "12"
        }
      ],
      [
        "line",
        {
          "x1": "6",
          "x2": "2",
          "y1": "12",
          "y2": "12"
        }
      ],
      [
        "line",
        {
          "x1": "12",
          "x2": "12",
          "y1": "6",
          "y2": "2"
        }
      ],
      [
        "line",
        {
          "x1": "12",
          "x2": "12",
          "y1": "22",
          "y2": "18"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "hexagon",
    "label": "Hexagon",
    "tags": [
      "shape",
      "geometric"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "triangle",
    "label": "Triangle",
    "tags": [
      "shape",
      "geometric"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M13.73 4a2 2 0 0 0-3.46 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "diamond",
    "label": "Diamond",
    "tags": [
      "shape",
      "geometric"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M2.7 10.3a2.41 2.41 0 0 0 0 3.41l7.59 7.59a2.41 2.41 0 0 0 3.41 0l7.59-7.59a2.41 2.41 0 0 0 0-3.41l-7.59-7.59a2.41 2.41 0 0 0-3.41 0Z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "hash",
    "label": "Hash",
    "tags": [
      "symbol",
      "tag"
    ],
    "nodes": [
      [
        "line",
        {
          "x1": "4",
          "x2": "20",
          "y1": "9",
          "y2": "9"
        }
      ],
      [
        "line",
        {
          "x1": "4",
          "x2": "20",
          "y1": "15",
          "y2": "15"
        }
      ],
      [
        "line",
        {
          "x1": "10",
          "x2": "8",
          "y1": "3",
          "y2": "21"
        }
      ],
      [
        "line",
        {
          "x1": "16",
          "x2": "14",
          "y1": "3",
          "y2": "21"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "at-sign",
    "label": "At",
    "tags": [
      "symbol",
      "social"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "4"
        }
      ],
      [
        "path",
        {
          "d": "M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-4 8"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "asterisk",
    "label": "Asterisk",
    "tags": [
      "symbol",
      "star"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M12 6v12"
        }
      ],
      [
        "path",
        {
          "d": "M17.196 9 6.804 15"
        }
      ],
      [
        "path",
        {
          "d": "m6.804 9 10.392 6"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "infinity",
    "label": "Infinity",
    "tags": [
      "symbol",
      "forever"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M12 12c-2-2.67-4-4-6-4a4 4 0 1 0 0 8c2 0 4-1.33 6-4Zm0 0c2 2.67 4 4 6 4a4 4 0 0 0 0-8c-2 0-4 1.33-6 4Z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "award",
    "label": "Award",
    "tags": [
      "win",
      "badge"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "m15.477 12.89 1.515 8.526a.5.5 0 0 1-.81.47l-3.58-2.687a1 1 0 0 0-1.197 0l-3.586 2.686a.5.5 0 0 1-.81-.469l1.514-8.526"
        }
      ],
      [
        "circle",
        {
          "cx": "12",
          "cy": "8",
          "r": "6"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "shield",
    "label": "Shield",
    "tags": [
      "protect",
      "crest",
      "badge"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "swords",
    "label": "Swords",
    "tags": [
      "battle",
      "crest",
      "edgy"
    ],
    "nodes": [
      [
        "polyline",
        {
          "points": "14.5 17.5 3 6 3 3 6 3 17.5 14.5"
        }
      ],
      [
        "line",
        {
          "x1": "13",
          "x2": "19",
          "y1": "19",
          "y2": "13"
        }
      ],
      [
        "line",
        {
          "x1": "16",
          "x2": "20",
          "y1": "16",
          "y2": "20"
        }
      ],
      [
        "line",
        {
          "x1": "19",
          "x2": "21",
          "y1": "21",
          "y2": "19"
        }
      ],
      [
        "polyline",
        {
          "points": "14.5 6.5 18 3 21 3 21 6 17.5 9.5"
        }
      ],
      [
        "line",
        {
          "x1": "5",
          "x2": "9",
          "y1": "14",
          "y2": "18"
        }
      ],
      [
        "line",
        {
          "x1": "7",
          "x2": "4",
          "y1": "17",
          "y2": "20"
        }
      ],
      [
        "line",
        {
          "x1": "3",
          "x2": "5",
          "y1": "19",
          "y2": "21"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "hand",
    "label": "Hand",
    "tags": [
      "wave",
      "hello"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M18 11V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2"
        }
      ],
      [
        "path",
        {
          "d": "M14 10V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2"
        }
      ],
      [
        "path",
        {
          "d": "M10 10.5V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2v8"
        }
      ],
      [
        "path",
        {
          "d": "M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "thumbs-up",
    "label": "Thumbs up",
    "tags": [
      "like",
      "approve"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M7 10v12"
        }
      ],
      [
        "path",
        {
          "d": "M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "eye",
    "label": "Eye",
    "tags": [
      "see",
      "watch"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"
        }
      ],
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "3"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "glasses",
    "label": "Glasses",
    "tags": [
      "cool",
      "style"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "6",
          "cy": "15",
          "r": "4"
        }
      ],
      [
        "circle",
        {
          "cx": "18",
          "cy": "15",
          "r": "4"
        }
      ],
      [
        "path",
        {
          "d": "M14 15a2 2 0 0 0-2-2 2 2 0 0 0-2 2"
        }
      ],
      [
        "path",
        {
          "d": "M2.5 13 5 7c.7-1.3 1.4-2 3-2"
        }
      ],
      [
        "path",
        {
          "d": "M21.5 13 19 7c-.7-1.3-1.5-2-3-2"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "scissors",
    "label": "Scissors",
    "tags": [
      "cut",
      "craft"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "6",
          "cy": "6",
          "r": "3"
        }
      ],
      [
        "path",
        {
          "d": "M8.12 8.12 12 12"
        }
      ],
      [
        "path",
        {
          "d": "M20 4 8.12 15.88"
        }
      ],
      [
        "circle",
        {
          "cx": "6",
          "cy": "18",
          "r": "3"
        }
      ],
      [
        "path",
        {
          "d": "M14.8 14.8 20 20"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "palette",
    "label": "Palette",
    "tags": [
      "art",
      "paint",
      "design"
    ],
    "nodes": [
      [
        "circle",
        {
          "cx": "13.5",
          "cy": "6.5",
          "r": ".5",
          "fill": "currentColor"
        }
      ],
      [
        "circle",
        {
          "cx": "17.5",
          "cy": "10.5",
          "r": ".5",
          "fill": "currentColor"
        }
      ],
      [
        "circle",
        {
          "cx": "8.5",
          "cy": "7.5",
          "r": ".5",
          "fill": "currentColor"
        }
      ],
      [
        "circle",
        {
          "cx": "6.5",
          "cy": "12.5",
          "r": ".5",
          "fill": "currentColor"
        }
      ],
      [
        "path",
        {
          "d": "M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "brush",
    "label": "Brush",
    "tags": [
      "art",
      "paint",
      "design"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "m9.06 11.9 8.07-8.06a2.85 2.85 0 1 1 4.03 4.03l-8.06 8.08"
        }
      ],
      [
        "path",
        {
          "d": "M7.07 14.94c-1.66 0-3 1.35-3 3.02 0 1.33-2.5 1.52-2 2.02 1.08 1.1 2.49 2.02 4 2.02 2.2 0 4-1.8 4-4.04a3.01 3.01 0 0 0-3-3.02z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "wand",
    "label": "Wand",
    "tags": [
      "magic",
      "sparkle"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M15 4V2"
        }
      ],
      [
        "path",
        {
          "d": "M15 16v-2"
        }
      ],
      [
        "path",
        {
          "d": "M8 9h2"
        }
      ],
      [
        "path",
        {
          "d": "M20 9h2"
        }
      ],
      [
        "path",
        {
          "d": "M17.8 11.8 19 13"
        }
      ],
      [
        "path",
        {
          "d": "M15 9h.01"
        }
      ],
      [
        "path",
        {
          "d": "M17.8 6.2 19 5"
        }
      ],
      [
        "path",
        {
          "d": "m3 21 9-9"
        }
      ],
      [
        "path",
        {
          "d": "M12.2 6.2 11 5"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "key",
    "label": "Key",
    "tags": [
      "unlock",
      "symbol"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4"
        }
      ],
      [
        "path",
        {
          "d": "m21 2-9.6 9.6"
        }
      ],
      [
        "circle",
        {
          "cx": "7.5",
          "cy": "15.5",
          "r": "5.5"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "lock",
    "label": "Lock",
    "tags": [
      "secure",
      "symbol"
    ],
    "nodes": [
      [
        "rect",
        {
          "width": "18",
          "height": "11",
          "x": "3",
          "y": "11",
          "rx": "2",
          "ry": "2"
        }
      ],
      [
        "path",
        {
          "d": "M7 11V7a5 5 0 0 1 10 0v4"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "bell",
    "label": "Bell",
    "tags": [
      "alert",
      "notify"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"
        }
      ],
      [
        "path",
        {
          "d": "M10.3 21a1.94 1.94 0 0 0 3.4 0"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "gift",
    "label": "Gift",
    "tags": [
      "present",
      "birthday",
      "party"
    ],
    "nodes": [
      [
        "rect",
        {
          "x": "3",
          "y": "8",
          "width": "18",
          "height": "4",
          "rx": "1"
        }
      ],
      [
        "path",
        {
          "d": "M12 8v13"
        }
      ],
      [
        "path",
        {
          "d": "M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7"
        }
      ],
      [
        "path",
        {
          "d": "M7.5 8a2.5 2.5 0 0 1 0-5A4.8 8 0 0 1 12 8a4.8 8 0 0 1 4.5-5 2.5 2.5 0 0 1 0 5"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "party-popper",
    "label": "Party",
    "tags": [
      "party",
      "celebrate",
      "owambe"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M5.8 11.3 2 22l10.7-3.79"
        }
      ],
      [
        "path",
        {
          "d": "M4 3h.01"
        }
      ],
      [
        "path",
        {
          "d": "M22 8h.01"
        }
      ],
      [
        "path",
        {
          "d": "M15 2h.01"
        }
      ],
      [
        "path",
        {
          "d": "M22 20h.01"
        }
      ],
      [
        "path",
        {
          "d": "m22 2-2.24.75a2.9 2.9 0 0 0-1.96 3.12c.1.86-.57 1.63-1.45 1.63h-.38c-.86 0-1.6.6-1.76 1.44L14 10"
        }
      ],
      [
        "path",
        {
          "d": "m22 13-.82-.33c-.86-.34-1.82.2-1.98 1.11c-.11.7-.72 1.22-1.43 1.22H17"
        }
      ],
      [
        "path",
        {
          "d": "m11 2 .33.82c.34.86-.2 1.82-1.11 1.98C9.52 4.9 9 5.52 9 6.23V7"
        }
      ],
      [
        "path",
        {
          "d": "M11 13c1.93 1.93 2.83 4.17 2 5-.83.83-3.07-.07-5-2-1.93-1.93-2.83-4.17-2-5 .83-.83 3.07.07 5 2Z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "cross",
    "label": "Cross",
    "tags": [
      "faith",
      "plus"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M4 9a2 2 0 0 0-2 2v2a2 2 0 0 0 2 2h4a1 1 0 0 1 1 1v4a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2v-4a1 1 0 0 1 1-1h4a2 2 0 0 0 2-2v-2a2 2 0 0 0-2-2h-4a1 1 0 0 1-1-1V4a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v4a1 1 0 0 1-1 1z"
        }
      ]
    ],
    "viewBox": 24
  },
  {
    "id": "venetian-mask",
    "label": "Mask",
    "tags": [
      "party",
      "carnival",
      "fun"
    ],
    "nodes": [
      [
        "path",
        {
          "d": "M2 12a5 5 0 0 0 5 5 8 8 0 0 1 5 2 8 8 0 0 1 5-2 5 5 0 0 0 5-5V7h-5a8 8 0 0 0-5 2 8 8 0 0 0-5-2H2Z"
        }
      ],
      [
        "path",
        {
          "d": "M6 11c1.5 0 3 .5 3 2-2 0-3 0-3-2Z"
        }
      ],
      [
        "path",
        {
          "d": "M18 11c-1.5 0-3 .5-3 2 2 0 3 0 3-2Z"
        }
      ]
    ],
    "viewBox": 24
  }
] as const as unknown as ReadonlyArray<IconDef>;

export const searchIcons = (query: string): IconDef[] => {
  const q = query.trim().toLowerCase();
  if (!q) return [...ICONS];
  return ICONS.filter(
    (i) => i.label.toLowerCase().includes(q) || i.id.includes(q) || i.tags.some((t) => t.includes(q)),
  );
};
